from institutions_synonyms import *

AFFILIATION_SYNONYMS = {
    "TUM": TUM_SYNONYMS,
    "KIT": KIT_SYNONYMS,
    "UNI_BONN": UNI_BONN_SYNONYMS,
    "TU_BERLIN": TU_BERLIN_SYNONYMS,
    "TU_DARMSTADT": TU_DARMSTADT_SYNONYMS,
    "UNI_BREMEN": UNI_BREMEN_SYNONYMS,
    "UNI_STUTTGART": UNI_STUTTGART_SYNONYMS,
    "RWTH_AACHEN": RWTH_AACHEN_SYNONYMS,
    "TU_DRESDEN": TU_DRESDEN_SYNONYMS,
    "UTN": UTN_SYNONYMS,
    "DLR": DLR_SYNONYMS,
    "MPI_IS": MPI_IS_SYNONYMS,
    "FRAUNHOFER_IPA": FRAUNHOFER_IPA_SYNONYMS,
    "FRAUNHOFER_IOSB": FRAUNHOFER_IOSB_SYNONYMS,
    "FRAUNHOFER_IML": FRAUNHOFER_IML_SYNONYMS,
    "DFKI": DFKI_SYNONYMS,
}